# Generated by Django 3.2.9 on 2021-12-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
        ),
    ]
