# Generated by Django 3.2.9 on 2021-12-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dwelling'),
        ('users', '0003_profile_profile_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_dwelling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dwelling'),
        ),
    ]
