# Generated by Django 3.2.9 on 2021-12-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maths', '0002_rename_highscoremodel_mathhighscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvMathScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default='0')),
                ('time', models.IntegerField(default='0')),
                ('formated_time', models.CharField(default='0', max_length=30)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score', 'time'),
            },
        ),
    ]
