# Generated by Django 3.2.9 on 2021-12-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_advmathscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMathScore',
            fields=[
                ('mathhighscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maths.mathhighscore')),
            ],
            bases=('maths.mathhighscore',),
        ),
    ]
