# Generated by Django 3.2.9 on 2021-12-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(default='house.svg', upload_to='pet_pics')),
                ('price', models.IntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
            ],
        ),
    ]
