# Generated by Django 3.2.9 on 2021-12-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dwelling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pet')),
            ],
            bases=('main.pet',),
        ),
    ]
